// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY_4gJdzTykyHCGjWN6VowOtm4KzXCr2M',
    appId: '1:1006948978372:web:567449752fc2520cc8c391',
    messagingSenderId: '1006948978372',
    projectId: 'geopaws-eaf88',
    authDomain: 'geopaws-eaf88.firebaseapp.com',
    storageBucket: 'geopaws-eaf88.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_4XuygsUNR-Xlc4nhqNNaGVa7ZZqJ260',
    appId: '1:1006948978372:android:e43f128a3febda0fc8c391',
    messagingSenderId: '1006948978372',
    projectId: 'geopaws-eaf88',
    storageBucket: 'geopaws-eaf88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9sI6gqJsOJDdIcXPhQnxugjHBIDyvJrU',
    appId: '1:1006948978372:ios:c4b177dedfabd250c8c391',
    messagingSenderId: '1006948978372',
    projectId: 'geopaws-eaf88',
    storageBucket: 'geopaws-eaf88.appspot.com',
    iosBundleId: 'com.example.geopawsfinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9sI6gqJsOJDdIcXPhQnxugjHBIDyvJrU',
    appId: '1:1006948978372:ios:9e09d2c220d244fdc8c391',
    messagingSenderId: '1006948978372',
    projectId: 'geopaws-eaf88',
    storageBucket: 'geopaws-eaf88.appspot.com',
    iosBundleId: 'com.example.geopawsfinal.RunnerTests',
  );
}
